#!/bin/sh

set -e

# Autopkgtest hook
if test -h js; then
	rm -f js
	echo "+ cp -s /usr/share/nodejs/bluebird/js"
	cp -r /usr/share/nodejs/bluebird/js .
fi

set -x
rm -rf node_modules || true
mkdir -p node_modules/bluebird/js/release
cp js/release/* node_modules/bluebird/js/release/ || true
cp package.json node_modules/bluebird/

# Some tests are failing/flaky. Therefore the following command
# cannot be run for now:
#node tools/test --no-js-hint
# Here are the failing tests (should try globbing them out to avoid
# testing each of the others separately):
#node tools/test --run=tapCatch.js
#node tools/test --run=generator.js
#node tools/test --run=getNewLibraryCopy.js
#node tools/test --run=long_stack_traces.js
# These tests work:
node --expose-gc tools/test --run=async.js --no-js-hint
#node tools/test --run=2.1.2.js --no-js-hint
#node tools/test --run=filter.js --no-js-hint
#node tools/test --run=tap.js --no-js-hint
#node tools/test --run=2.1.3.js --no-js-hint
#node tools/test --run=finally.js --no-js-hint
#node tools/test --run=2.2.1.js --no-js-hint
#node tools/test --run=following.js --no-js-hint
#node tools/test --run=timers.js --no-js-hint
#node tools/test --run=2.2.2.js --no-js-hint
#node tools/test --run=try.js --no-js-hint
#node tools/test --run=2.2.3.js --no-js-hint
#node tools/test --run=get.js --no-js-hint
#node tools/test --run=unhandled_rejections.js --no-js-hint
#node tools/test --run=2.2.4.js --no-js-hint
#node tools/test --run=using.js --no-js-hint
#node tools/test --run=2.2.5.js --no-js-hint
#node tools/test --run=github-2xx-76.js --no-js-hint
#node tools/test --run=2.2.6.js --no-js-hint
#node tools/test --run=github-3.6.4.js --no-js-hint
#node tools/test --run=2.2.7.js --no-js-hint
#node tools/test --run=github-3.7.3.js --no-js-hint
#node tools/test --run=2.3.1.js --no-js-hint
#node tools/test --run=github-4.1.7.js --no-js-hint
#node tools/test --run=2.3.2.js --no-js-hint
#node tools/test --run=github36.js --no-js-hint
#node tools/test --run=2.3.3.js --no-js-hint
#node tools/test --run=is.js --no-js-hint
#node tools/test --run=2.3.4.js --no-js-hint
#node tools/test --run=join.js --no-js-hint
#node tools/test --run=3.2.1.js --no-js-hint
#node tools/test --run=late_buffer_safety.js --no-js-hint
#node tools/test --run=3.2.2.js --no-js-hint
#node tools/test --run=3.2.3.js --no-js-hint
#node tools/test --run=map.js --no-js-hint
#node tools/test --run=3.2.4.js --no-js-hint
#node tools/test --run=method.js --no-js-hint
#node tools/test --run=3.2.5.js --no-js-hint
#node tools/test --run=monitoring.js --no-js-hint
node tools/test --run=3.2.6.js --no-js-hint
node tools/test --run=multiple-copies.js --no-js-hint
node tools/test --run=any.js --no-js-hint
#node tools/test --run=no_conflict.js --no-js-hint
node tools/test --run=api_exceptions.js --no-js-hint
#node tools/test --run=nodeify.js --no-js-hint
node tools/test --run=promise_array.js --no-js-hint
node tools/test --run=bind.js --no-js-hint
node tools/test --run=promisify.js --no-js-hint
node tools/test --run=bluebird-multiple-instances.js --no-js-hint
node tools/test --run=props.js --no-js-hint
node tools/test --run=call.js --no-js-hint
node tools/test --run=race.js --no-js-hint
node tools/test --run=cancel.js --no-js-hint
node tools/test --run=reduce.js --no-js-hint
node tools/test --run=catch_filter.js --no-js-hint
node tools/test --run=reflect.js --no-js-hint
node tools/test --run=collections_thenables.js --no-js-hint
node tools/test --run=regress.js --no-js-hint
node tools/test --run=constructor.js --no-js-hint
node tools/test --run=rejections.js --no-js-hint
node tools/test --run=cycles.js --no-js-hint
node tools/test --run=resolution.js --no-js-hint
node tools/test --run=direct_resolving.js --no-js-hint
node tools/test --run=schedule.js --no-js-hint
node tools/test --run=domain.js --no-js-hint
node tools/test --run=settle.js --no-js-hint
node tools/test --run=done.js --no-js-hint
node tools/test --run=some.js --no-js-hint
node tools/test --run=each.js --no-js-hint
node tools/test --run=spread.js --no-js-hint
node tools/test --run=error.js --no-js-hint
node tools/test --run=synchronous_inspection.js --no-js-hint
# tools/test.js builds a debug version of bluebird (ovewriting the
# release version in dh_auto_build. A quick fix is to build the
# release version of bluebird again for dh_install to use.
node tools/build.js --release --no-minify
rm -rf node_modules/bluebird/ || true
rmdir node_modules || true
